### ISSUE TITLE
Failed container start fails with a type error on Python 3

### ISSUE THREAD

**Issue by justanr** [signalfx/maestro-ng#197]
When we have a container fail to start in the time allotted for a life cycle check, the entire operation fails with an exception instead of reporting the error itself.

Here is the relevant traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/maestro/__main__.py", line 173, in execute
    getattr(c, options.command)(**vars(options))
  File "/usr/local/lib/python3.6/site-packages/maestro/maestro.py", line 305, in start
    auditor=self.auditor).run()
  File "/usr/local/lib/python3.6/site-packages/maestro/plays/__init__.py", line 160, in run
    self._end()
  File "/usr/local/lib/python3.6/site-packages/maestro/plays/__init__.py", line 148, in _end
    exceptions.raise_with_tb(self._error)
  File "/usr/local/lib/python3.6/site-packages/maestro/exceptions.py", line 20, in raise_with_tb
    raise info[1].with_traceback(info[2])
  File "/usr/local/lib/python3.6/site-packages/maestro/plays/__init__.py", line 99, in act
    task.run(auditor=self._auditor)
  File "/usr/local/lib/python3.6/site-packages/maestro/plays/tasks.py", line 95, in run
    exceptions.raise_with_tb()
  File "/usr/local/lib/python3.6/site-packages/maestro/exceptions.py", line 20, in raise_with_tb
    raise info[1].with_traceback(info[2])
  File "/usr/local/lib/python3.6/site-packages/maestro/plays/tasks.py", line 87, in run
    self._run()
  File "/usr/local/lib/python3.6/site-packages/maestro/plays/tasks.py", line 164, in _run
    self.container, '\n'.join(error).strip())
TypeError: sequence item 1: expected str instance, bytes found
```

And it looks like [this might be the offending line](https://github.com/signalfx/maestro-ng/blob/d506efdb0e77ddcb7c8771d2e683cfb0612d4910/maestro/plays/tasks.py#L163)

Environment:

* Python 3.6
* Debian inside Docker
* maestro-ng ==0.4.4

**Comment by justanr** [comment]
Thanks!
