### ISSUE TITLE
Ubuntu 14.04 - pip broken after installation

### ISSUE THREAD

**Issue by balokir** [signalfx/maestro-ng#99]
I use Ubuntu 14.04 and try to install the maestro-ng.

`root@e007aeab14ae:~#  pip install --upgrade git+git://github.com/signalfuse/maestro-ng
...
Successfully installed docker-py pyyaml jinja2 six bgtunnel python-simple-hipchat maestro requests websocket-client markupsafe backports.ssl-match-hostname  
Cleaning up...`
The installation passed without any errors but I found two strange things.
**The first** - maestro: command not found
  root@e007aeab14ae:~#  maestro
  maestro: command not found

**The second** - pip now broken as described at https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1306991

  root@e007aeab14ae:~# pip
  Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/python2.7/dist-packages/pip/**init**.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url  
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead 
  ImportError: cannot import name IncompleteRead

**Comment by keevee09** [comment]
@balokir Your solution worked for me.
I had performed:
$sudo pip install --U virtualenvs
and after pip broke on the version number check in:
"/usr/local/lib/python3.4/dist-packages/distribute-0.6.49-py3.4.egg/pkg_resources.py", line 596, in resolve etc.
whenever I tried, say:
$pip list
